from typing import Any, Callable, Dict, Optional, Sequence


def base_eval_result(
    *,
    seed_accuracy_baseline: Optional[float] = None,
    eval_limit_seconds: Optional[int] = None,
    backbone_model_names: Optional[list[str]] = None,
    formal_reward_epochs: Sequence[int],
) -> Dict[str, Any]:
    return {
        "val_metric": None,
        "test_acc": None,
        "built_ok": False,
        "forward_ok": False,
        "forward_shape_ok": False,
        "trained_step_ok": False,
        "backward_ok": False,
        "loss_start": None,
        "loss_end": None,
        "loss_drop": None,
        "loss_drop_ok": False,
        "best_epoch_loss": None,
        "avg_epoch_loss": None,
        "epochs_completed": 0,
        "epoch_loss_series": [],
        "training_context_metric_name": "best_epoch_loss",
        "training_context_metric_value": None,
        "train_acc": None,
        "seed_accuracy_baseline": seed_accuracy_baseline,
        "seed_train_acc_gap": None,
        "seed_train_acc_improved": False,
        "accuracy_baseline": seed_accuracy_baseline,
        "train_acc_gain": None,
        "train_acc_improved": False,
        "group_baseline_train_acc": None,
        "group_train_acc_gain": None,
        "group_train_acc_improved": False,
        "reward_batch_index": None,
        "reward_group_id": None,
        "group_warmup": False,
        "latency_ms": None,
        "params_m": None,
        "timed_out": False,
        "estimated_total_seconds": None,
        "eval_limit_seconds": eval_limit_seconds,
        "warmup_dense_reward": None,
        "backbone_model_names": list(backbone_model_names or []),
        "frozen_train_acc": None,
        "frozen_test_acc": None,
        "unfrozen_train_acc": None,
        "unfrozen_test_acc": None,
        "frozen_eval": None,
        "unfrozen_eval": None,
        "reward_target_metric": "frozen_test_acc",
        "reward_target_value": None,
        "formal_reward_epochs": list(formal_reward_epochs),
        "formal_reward_max_epoch": int(max(formal_reward_epochs)),
        "formal_horizon_test_acc": {},
        "formal_horizon_train_acc": {},
        "formal_horizon_scores": {},
        "formal_reward_target_value": None,
        "error_type": None,
        "error_stage": None,
        "error_context": None,
        "error_hint": None,
    }


def nested_eval_payload(
    result: Optional[Dict[str, Any]],
    *,
    eval_mode: str,
    backbone_frozen: bool,
) -> Optional[Dict[str, Any]]:
    if result is None:
        return None
    return {
        "eval_mode": eval_mode,
        "backbone_frozen": backbone_frozen,
        "reward": result.get("reward"),
        "components": dict(result.get("components") or {}),
        "built_ok": result.get("built_ok"),
        "forward_ok": result.get("forward_ok"),
        "forward_shape_ok": result.get("forward_shape_ok"),
        "trained_step_ok": result.get("trained_step_ok"),
        "backward_ok": result.get("backward_ok"),
        "loss_start": result.get("loss_start"),
        "loss_end": result.get("loss_end"),
        "loss_drop": result.get("loss_drop"),
        "loss_drop_ok": result.get("loss_drop_ok"),
        "best_epoch_loss": result.get("best_epoch_loss"),
        "avg_epoch_loss": result.get("avg_epoch_loss"),
        "epochs_completed": result.get("epochs_completed"),
        "epoch_loss_series": list(result.get("epoch_loss_series") or []),
        "training_context_metric_name": result.get("training_context_metric_name"),
        "training_context_metric_value": result.get("training_context_metric_value"),
        "train_acc": result.get("train_acc"),
        "test_acc": result.get("test_acc", result.get("val_metric")),
        "val_metric": result.get("val_metric"),
        "latency_ms": result.get("latency_ms"),
        "params_m": result.get("params_m"),
        "timed_out": result.get("timed_out", False),
        "estimated_total_seconds": result.get("estimated_total_seconds"),
        "eval_limit_seconds": result.get("eval_limit_seconds"),
        "backbone_model_names": list(result.get("backbone_model_names") or []),
        "seed_accuracy_baseline": result.get("seed_accuracy_baseline"),
        "seed_train_acc_gap": result.get("seed_train_acc_gap"),
        "seed_train_acc_improved": result.get("seed_train_acc_improved"),
        "formal_reward_epochs": list(result.get("formal_reward_epochs") or []),
        "formal_reward_max_epoch": result.get("formal_reward_max_epoch"),
        "formal_horizon_test_acc": dict(result.get("formal_horizon_test_acc") or {}),
        "formal_horizon_train_acc": dict(result.get("formal_horizon_train_acc") or {}),
        "formal_horizon_scores": dict(result.get("formal_horizon_scores") or {}),
        "formal_reward_target_value": result.get("formal_reward_target_value"),
        "error": result.get("error"),
        "error_type": result.get("error_type"),
        "error_stage": result.get("error_stage"),
        "error_context": dict(result.get("error_context") or {}) if result.get("error_context") is not None else None,
        "error_hint": result.get("error_hint"),
    }


def merge_dual_eval_results(
    *,
    frozen_result: Dict[str, Any],
    unfrozen_result: Optional[Dict[str, Any]],
    reward_target_metric: str,
    formal_multi_horizon_reward_target_metric: str,
    coerce_optional_metric_float: Callable[[Any], Optional[float]],
) -> Dict[str, Any]:
    del unfrozen_result
    merged = dict(frozen_result)
    frozen_train_acc = frozen_result.get("train_acc")
    frozen_test_acc = frozen_result.get("test_acc", frozen_result.get("val_metric"))
    reward_target_metric = str(reward_target_metric or "frozen_test_acc")
    if reward_target_metric not in {
        "frozen_test_acc",
        "frozen_train_acc",
        formal_multi_horizon_reward_target_metric,
    }:
        reward_target_metric = "frozen_test_acc"

    if reward_target_metric == formal_multi_horizon_reward_target_metric:
        reward_target_value = coerce_optional_metric_float(frozen_result.get("formal_reward_target_value"))
    elif reward_target_metric == "frozen_test_acc":
        reward_target_value = frozen_test_acc
    else:
        reward_target_value = frozen_train_acc

    merged.update(
        {
            "test_acc": frozen_test_acc,
            "train_acc": frozen_train_acc,
            "val_metric": frozen_test_acc,
            "frozen_train_acc": frozen_train_acc,
            "frozen_test_acc": frozen_test_acc,
            "unfrozen_train_acc": None,
            "unfrozen_test_acc": None,
            "frozen_eval": nested_eval_payload(
                frozen_result,
                eval_mode="frozen",
                backbone_frozen=True,
            ),
            "unfrozen_eval": None,
            "reward_target_metric": reward_target_metric,
            "reward_target_value": reward_target_value,
            "formal_reward_epochs": list(frozen_result.get("formal_reward_epochs") or []),
            "formal_reward_max_epoch": frozen_result.get("formal_reward_max_epoch"),
            "formal_horizon_test_acc": dict(frozen_result.get("formal_horizon_test_acc") or {}),
            "formal_horizon_train_acc": dict(frozen_result.get("formal_horizon_train_acc") or {}),
            "formal_horizon_scores": dict(frozen_result.get("formal_horizon_scores") or {}),
            "formal_reward_target_value": coerce_optional_metric_float(
                frozen_result.get("formal_reward_target_value")
            ),
        }
    )
    return merged


def empty_eval_result(
    *,
    reward: float = 0.0,
    error: Optional[str] = None,
    seed_accuracy_baseline: Optional[float] = None,
    eval_limit_seconds: Optional[int] = None,
    backbone_model_names: Optional[list[str]] = None,
    formal_reward_epochs: Sequence[int],
) -> Dict[str, Any]:
    components = {
        "reward": reward,
        "r_build": 0.0,
        "r_forward_shape": 0.0,
        "r_backward": 0.0,
        "r_loss_drop": 0.0,
        "r_forward": 0.0,
        "r_trainstep": 0.0,
        "r_metric": 0.0,
        "r_eff": 0.0,
        "r_critic": 0.0,
        "r_kl": 0.0,
    }
    result = {
        "reward": reward,
        "components": components,
        **base_eval_result(
            seed_accuracy_baseline=seed_accuracy_baseline,
            eval_limit_seconds=eval_limit_seconds,
            backbone_model_names=backbone_model_names,
            formal_reward_epochs=formal_reward_epochs,
        ),
    }
    if error:
        result["error"] = error
    return result


def timeout_eval_result(
    *,
    components: Dict[str, Any],
    error: str,
    estimated_total_seconds: Optional[float],
    eval_limit_seconds: Optional[int],
    seed_accuracy_baseline: Optional[float] = None,
    backbone_model_names: Optional[list[str]] = None,
    built_ok: bool = False,
    forward_ok: bool = False,
    forward_shape_ok: bool = False,
    trained_step_ok: bool = False,
    backward_ok: bool = False,
    loss_start: Optional[float] = None,
    loss_end: Optional[float] = None,
    loss_drop: Optional[float] = None,
    loss_drop_ok: bool = False,
    best_epoch_loss: Optional[float] = None,
    avg_epoch_loss: Optional[float] = None,
    epochs_completed: int = 0,
    epoch_loss_series: Optional[list[float]] = None,
    training_context_metric_name: Optional[str] = "best_epoch_loss",
    training_context_metric_value: Optional[float] = None,
    latency_ms: Optional[float] = None,
    params_m: Optional[float] = None,
    formal_reward_epochs: Sequence[int],
) -> Dict[str, Any]:
    return {
        "reward": components["reward"],
        "components": components,
        **{
            **base_eval_result(
                seed_accuracy_baseline=seed_accuracy_baseline,
                eval_limit_seconds=eval_limit_seconds,
                backbone_model_names=backbone_model_names,
                formal_reward_epochs=formal_reward_epochs,
            ),
            "built_ok": built_ok,
            "forward_ok": forward_ok,
            "forward_shape_ok": forward_shape_ok,
            "trained_step_ok": trained_step_ok,
            "backward_ok": backward_ok,
            "loss_start": loss_start,
            "loss_end": loss_end,
            "loss_drop": loss_drop,
            "loss_drop_ok": loss_drop_ok,
            "best_epoch_loss": best_epoch_loss,
            "avg_epoch_loss": avg_epoch_loss,
            "epochs_completed": int(epochs_completed or 0),
            "epoch_loss_series": list(epoch_loss_series or []),
            "training_context_metric_name": training_context_metric_name,
            "training_context_metric_value": training_context_metric_value,
            "latency_ms": latency_ms,
            "params_m": params_m,
            "timed_out": True,
            "estimated_total_seconds": estimated_total_seconds,
            "error": error,
        },
    }


def setdefault_many(target: Dict[str, Any], defaults: Dict[str, Any]) -> None:
    for key, value in defaults.items():
        target.setdefault(key, value)


def attach_group_context(
    rl: Any,
    res: Dict[str, Any],
    *,
    seed_accuracy_baseline: float,
    group_context: Dict[str, Any],
) -> Dict[str, Any]:
    frozen_train_acc = rl._optional_float(res.get("frozen_train_acc", res.get("train_acc")))
    frozen_test_acc = rl._optional_float(res.get("frozen_test_acc", res.get("test_acc", res.get("val_metric"))))
    setdefault_many(
        res,
        {
            "test_acc": frozen_test_acc,
            "frozen_train_acc": frozen_train_acc,
            "frozen_test_acc": frozen_test_acc,
            "unfrozen_train_acc": None,
            "unfrozen_test_acc": None,
            "frozen_eval": None,
            "unfrozen_eval": None,
            "seed_accuracy_baseline": seed_accuracy_baseline,
            "seed_train_acc_gap": None,
            "seed_train_acc_improved": False,
            "accuracy_baseline": seed_accuracy_baseline,
            "train_acc_gain": None,
            "train_acc_improved": False,
            "group_baseline_train_acc": group_context["group_baseline_train_acc"],
            "global_group_baseline_reward_target_acc": group_context["group_baseline_reward_target_acc"],
            "group_train_acc_gain": None,
            "group_train_acc_improved": False,
            "reward_target_metric": rl._stage_reward_target_metric(group_context.get("current_stage_name", rl.current_stage_name)),
            "reward_target_value": rl._result_reward_target_value(res),
            "best_epoch_loss": None,
            "avg_epoch_loss": None,
            "epochs_completed": 0,
            "epoch_loss_series": [],
            "training_context_metric_name": "best_epoch_loss",
            "training_context_metric_value": None,
            "group_baseline_reward_target_acc": group_context["group_baseline_reward_target_acc"],
            "group_backbone_baseline_reward_target_acc": None,
            "group_reward_target_gain": None,
            "group_reward_target_improved": False,
            "backbone_reward_target_gain": None,
            "backbone_reward_target_improved": False,
            "reward_batch_index": group_context["reward_batch_index"],
            "reward_group_id": group_context["reward_group_id"],
            "group_warmup": group_context["group_warmup"],
            "timed_out": False,
            "estimated_total_seconds": None,
            "eval_limit_seconds": None,
            "warmup_dense_reward": None,
            "backbone_model_names": [],
            "best_closed_group_mean_reward_target_acc": group_context["best_closed_group_mean_reward_target_acc"],
            "best_closed_group_mean_train_acc": group_context["best_closed_group_mean_train_acc"],
            "best_closed_group_mean_test_acc": group_context["best_closed_group_mean_test_acc"],
            "best_backbone_group_mean_reward_target_acc": None,
            "best_reward_target_for_goal": None,
            "r_dense": 0.0,
            "r_prev_group": 0.0,
            "r_best_group": 0.0,
            "r_prev_backbone_group": 0.0,
            "r_best_backbone_group": 0.0,
            "r_goal_best": 0.0,
            "r_goal_match": 0.0,
            "r_trainset_novelty": 0.0,
            "r_generalization": 0.0,
            "r_structure_group": 0.0,
            "r_structure_archive": 0.0,
            "r_descriptor_diversity": 0.0,
            "r_cnn_diversity": 0.0,
            "r_batch_elite": 0.0,
            "r_repeat_family": 0.0,
            "r_plain_fuse_penalty": 0.0,
            "r_template_penalty": 0.0,
            "r_history_context": 0.0,
            "r_no_progress_penalty": 0.0,
            "batch_elite_rank": None,
            "batch_elite_tier": "none",
            "batch_elite_threshold_passed": False,
            "goal_tag_hit_count": 0,
            "goal_tag_total_count": 0,
            "goal_tag_hit_rate": 0.0,
            "prev_target_reward_target_acc": None,
            "best_target_reward_target_acc": None,
            "backbone_prev_target_reward_target_acc": None,
            "backbone_best_target_reward_target_acc": None,
            "prev_target_train_acc": None,
            "best_target_train_acc": None,
            "backbone_signature": rl.build_backbone_signature(res.get("backbone_model_names")),
            "cnn_signature": str(res.get("cnn_signature") or ""),
            "cnn_expr": str(res.get("cnn_expr") or ""),
        },
    )

    open_discovery = res.setdefault("open_discovery", {})
    setdefault_many(
        open_discovery,
        {
            "r_primary": 0.0,
            "r_tiebreak": 0.0,
            "r_trainset_novelty": res.get("r_trainset_novelty", 0.0),
            "r_dense": res.get("r_dense", 0.0),
            "r_prev_group": res.get("r_prev_group", 0.0),
            "r_best_group": res.get("r_best_group", 0.0),
            "r_prev_backbone_group": res.get("r_prev_backbone_group", 0.0),
            "r_best_backbone_group": res.get("r_best_backbone_group", 0.0),
            "r_goal_best": res.get("r_goal_best", 0.0),
            "r_goal_match": res.get("r_goal_match", 0.0),
            "r_generalization": res.get("r_generalization", 0.0),
            "r_structure_group": res.get("r_structure_group", 0.0),
            "r_structure_archive": res.get("r_structure_archive", 0.0),
            "r_descriptor_diversity": res.get("r_descriptor_diversity", 0.0),
            "r_cnn_diversity": res.get("r_cnn_diversity", 0.0),
            "r_batch_elite": res.get("r_batch_elite", 0.0),
            "r_repeat_family": res.get("r_repeat_family", 0.0),
            "r_plain_fuse_penalty": res.get("r_plain_fuse_penalty", 0.0),
            "r_template_penalty": res.get("r_template_penalty", 0.0),
            "r_history_context": res.get("r_history_context", 0.0),
            "r_no_progress_penalty": res.get("r_no_progress_penalty", 0.0),
            "batch_elite_rank": res.get("batch_elite_rank"),
            "batch_elite_tier": res.get("batch_elite_tier", "none"),
            "batch_elite_threshold_passed": res.get("batch_elite_threshold_passed", False),
            "novel_vs_trainset_family": False,
            "novel_vs_trainset_graph": False,
            "archive_snapshot_family_freq": 0,
            "batch_same_family_count": 0,
            "group_baseline_train_acc": group_context["group_baseline_train_acc"],
            "group_baseline_reward_target_acc": group_context["group_baseline_reward_target_acc"],
            "global_group_baseline_reward_target_acc": group_context["group_baseline_reward_target_acc"],
            "group_backbone_baseline_reward_target_acc": res.get("group_backbone_baseline_reward_target_acc"),
            "best_closed_group_mean_train_acc": group_context["best_closed_group_mean_train_acc"],
            "best_closed_group_mean_reward_target_acc": group_context["best_closed_group_mean_reward_target_acc"],
            "best_closed_group_mean_test_acc": group_context["best_closed_group_mean_test_acc"],
            "best_backbone_group_mean_reward_target_acc": res.get("best_backbone_group_mean_reward_target_acc"),
            "prev_target_train_acc": res.get("prev_target_train_acc"),
            "best_target_train_acc": res.get("best_target_train_acc"),
            "group_train_acc_gain": res.get("group_train_acc_gain"),
            "group_train_acc_improved": res.get("group_train_acc_improved", False),
            "reward_target_metric": res.get("reward_target_metric", rl._stage_reward_target_metric(rl.current_stage_name)),
            "reward_target_value": res.get("reward_target_value"),
            "group_reward_target_gain": res.get("group_reward_target_gain"),
            "group_reward_target_improved": res.get("group_reward_target_improved", False),
            "backbone_reward_target_gain": res.get("backbone_reward_target_gain"),
            "backbone_reward_target_improved": res.get("backbone_reward_target_improved", False),
            "goal_tag_hit_count": res.get("goal_tag_hit_count", 0),
            "goal_tag_total_count": res.get("goal_tag_total_count", 0),
            "goal_tag_hit_rate": res.get("goal_tag_hit_rate", 0.0),
            "prev_target_reward_target_acc": res.get("prev_target_reward_target_acc"),
            "best_target_reward_target_acc": res.get("best_target_reward_target_acc"),
            "backbone_prev_target_reward_target_acc": res.get("backbone_prev_target_reward_target_acc"),
            "backbone_best_target_reward_target_acc": res.get("backbone_best_target_reward_target_acc"),
            "reward_batch_index": group_context["reward_batch_index"],
            "reward_group_id": group_context["reward_group_id"],
            "group_warmup": group_context["group_warmup"],
            "current_stage_name": group_context.get("current_stage_name", rl.current_stage_name),
            "current_stage_index": group_context.get("current_stage_index", rl._current_stage_index()),
            "stage_uses_formal_eval": rl._stage_uses_formal_eval(group_context.get("current_stage_name", rl.current_stage_name)),
            "stage_uses_static_only": rl._stage_uses_static_only(group_context.get("current_stage_name", rl.current_stage_name)),
            "backbone_signature": res.get("backbone_signature", rl.build_backbone_signature(res.get("backbone_model_names"))),
            "cnn_signature": res.get("cnn_signature", ""),
            "cnn_expr": res.get("cnn_expr", ""),
        },
    )
    return res
